package javaweb.Entity;
// Generated Apr 11, 2021, 1:55:39 PM by Hibernate Tools 5.1.10.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BillHasProduct generated by hbm2java
 */
@Entity
@Table(name = "bill_has_product", catalog = "mydb")
public class BillHasProduct implements java.io.Serializable {

	private BillHasProductId id;
	private Bill bill;
	private Product product;
	private int ammount;
	private BigDecimal value;

	public BillHasProduct() {
	}

	public BillHasProduct(BillHasProductId id, Bill bill, Product product, int ammount, BigDecimal value) {
		this.id = id;
		this.bill = bill;
		this.product = product;
		this.ammount = ammount;
		this.value = value;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "billId", column = @Column(name = "BILL_ID", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "PRODUCT_ID", nullable = false)) })
	public BillHasProductId getId() {
		return this.id;
	}

	public void setId(BillHasProductId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BILL_ID", nullable = false, insertable = false, updatable = false)
	public Bill getBill() {
		return this.bill;
	}

	public void setBill(Bill bill) {
		this.bill = bill;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "AMMOUNT", nullable = false)
	public int getAmmount() {
		return this.ammount;
	}

	public void setAmmount(int ammount) {
		this.ammount = ammount;
	}

	@Column(name = "VALUE", nullable = false, precision = 20)
	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

}
