package javaweb.Entity;
// Generated Apr 11, 2021, 1:55:39 PM by Hibernate Tools 5.1.10.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name = "bill", catalog = "mydb")
public class Bill implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Commune commune;
	private Promotion promotion;
	private BigDecimal totalValue;
	private Set<BillHasProduct> billHasProducts = new HashSet<BillHasProduct>(0);

	public Bill() {
	}

	public Bill(Account account, Commune commune, BigDecimal totalValue) {
		this.account = account;
		this.commune = commune;
		this.totalValue = totalValue;
	}

	public Bill(Account account, Commune commune, Promotion promotion, BigDecimal totalValue,
			Set<BillHasProduct> billHasProducts) {
		this.account = account;
		this.commune = commune;
		this.promotion = promotion;
		this.totalValue = totalValue;
		this.billHasProducts = billHasProducts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_USERNAME", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMMUNE_ID", nullable = false)
	public Commune getCommune() {
		return this.commune;
	}

	public void setCommune(Commune commune) {
		this.commune = commune;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROMOTION_ID")
	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	@Column(name = "TOTAL_VALUE", nullable = false, precision = 20)
	public BigDecimal getTotalValue() {
		return this.totalValue;
	}

	public void setTotalValue(BigDecimal totalValue) {
		this.totalValue = totalValue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bill")
	public Set<BillHasProduct> getBillHasProducts() {
		return this.billHasProducts;
	}

	public void setBillHasProducts(Set<BillHasProduct> billHasProducts) {
		this.billHasProducts = billHasProducts;
	}

}
