package javaweb.Entity;
// Generated Apr 27, 2021, 11:12:42 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Color generated by hbm2java
 */
@Entity
@Table(name = "color", catalog = "mydb")
@JsonIgnoreProperties(value = {"productHasColors"})
public class Color implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private Set<ProductHasColor> productHasColors = new HashSet<ProductHasColor>(0);

	public Color() {
	}

	public Color(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Color(int id, String name, Set<ProductHasColor> productHasColors) {
		this.id = id;
		this.name = name;
		this.productHasColors = productHasColors;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = true, insertable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
	public Set<ProductHasColor> getProductHasColors() {
		return this.productHasColors;
	}

	public void setProductHasColors(Set<ProductHasColor> productHasColors) {
		this.productHasColors = productHasColors;
	}

}
