package javaweb.Entity;
// Generated Apr 27, 2021, 11:12:42 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductHasColorId generated by hbm2java
 */
@Embeddable
public class ProductHasColorId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int colorId;
	private int productId;

	public ProductHasColorId() {
	}

	public ProductHasColorId(int colorId, int productId) {
		this.colorId = colorId;
		this.productId = productId;
	}

	@Column(name = "COLOR_ID", nullable = false)
	public int getColorId() {
		return this.colorId;
	}

	public void setColorId(int colorId) {
		this.colorId = colorId;
	}

	@Column(name = "PRODUCT_ID", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductHasColorId))
			return false;
		ProductHasColorId castOther = (ProductHasColorId) other;

		return (this.getColorId() == castOther.getColorId()) && (this.getProductId() == castOther.getProductId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getColorId();
		result = 37 * result + this.getProductId();
		return result;
	}

}
