package javaweb.Entity;
// Generated Apr 11, 2021, 1:55:39 PM by Hibernate Tools 5.1.10.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "mydb")
public class Product implements java.io.Serializable {

	private Integer id;
	private String name;
	private BigDecimal originalPrice;
	private BigDecimal price;
	private BigDecimal promotionPrice;
	private String image;
	private String description;
	private Set<Category> categories = new HashSet<Category>(0);
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<BillHasProduct> billHasProducts = new HashSet<BillHasProduct>(0);
	private Set<Rating> ratings = new HashSet<Rating>(0);
	private Set<Color> colors = new HashSet<Color>(0);

	public Product() {
	}

	public Product(String name, BigDecimal originalPrice, BigDecimal price, BigDecimal promotionPrice) {
		this.name = name;
		this.originalPrice = originalPrice;
		this.price = price;
		this.promotionPrice = promotionPrice;
	}

	public Product(String name, BigDecimal originalPrice, BigDecimal price, BigDecimal promotionPrice, String image,
			String description, Set<Category> categories, Set<Comment> comments, Set<BillHasProduct> billHasProducts,
			Set<Rating> ratings, Set<Color> colors) {
		this.name = name;
		this.originalPrice = originalPrice;
		this.price = price;
		this.promotionPrice = promotionPrice;
		this.image = image;
		this.description = description;
		this.categories = categories;
		this.comments = comments;
		this.billHasProducts = billHasProducts;
		this.ratings = ratings;
		this.colors = colors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ORIGINAL_PRICE", nullable = false, precision = 20)
	public BigDecimal getOriginalPrice() {
		return this.originalPrice;
	}

	public void setOriginalPrice(BigDecimal originalPrice) {
		this.originalPrice = originalPrice;
	}

	@Column(name = "PRICE", nullable = false, precision = 20)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "PROMOTION_PRICE", nullable = false, precision = 20)
	public BigDecimal getPromotionPrice() {
		return this.promotionPrice;
	}

	public void setPromotionPrice(BigDecimal promotionPrice) {
		this.promotionPrice = promotionPrice;
	}

	@Column(name = "IMAGE", length = 500)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "product_has_category", catalog = "mydb", joinColumns = {
			@JoinColumn(name = "PRODUCT_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "CATEGORY_ID", nullable = false, updatable = false) })
	public Set<Category> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<BillHasProduct> getBillHasProducts() {
		return this.billHasProducts;
	}

	public void setBillHasProducts(Set<BillHasProduct> billHasProducts) {
		this.billHasProducts = billHasProducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Rating> getRatings() {
		return this.ratings;
	}

	public void setRatings(Set<Rating> ratings) {
		this.ratings = ratings;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "product_has_color", catalog = "mydb", joinColumns = {
			@JoinColumn(name = "PRODUCT_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "COLOR_ID", nullable = false, updatable = false) })
	public Set<Color> getColors() {
		return this.colors;
	}

	public void setColors(Set<Color> colors) {
		this.colors = colors;
	}

}
