package javaweb.Entity;
// Generated Apr 27, 2021, 11:12:42 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductHasColorHasBill generated by hbm2java
 */
@Entity
@Table(name = "product_has_color_has_bill", catalog = "mydb")
public class ProductHasColorHasBill implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ProductHasColorHasBillId id;
	private Bill bill;
	private ProductHasColor productHasColor;
	private Integer amount;

	public ProductHasColorHasBill() {
	}

	public ProductHasColorHasBill(ProductHasColorHasBillId id, Bill bill, ProductHasColor productHasColor) {
		this.id = id;
		this.bill = bill;
		this.productHasColor = productHasColor;
	}

	public ProductHasColorHasBill(ProductHasColorHasBillId id, Bill bill, ProductHasColor productHasColor,
			Integer amount) {
		this.id = id;
		this.bill = bill;
		this.productHasColor = productHasColor;
		this.amount = amount;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productHasColorColorId", column = @Column(name = "PRODUCT_has_COLOR_COLOR_ID", nullable = false)),
			@AttributeOverride(name = "productHasColorProductId", column = @Column(name = "PRODUCT_has_COLOR_PRODUCT_ID", nullable = false)),
			@AttributeOverride(name = "billId", column = @Column(name = "BILL_ID", nullable = false)) })
	public ProductHasColorHasBillId getId() {
		return this.id;
	}

	public void setId(ProductHasColorHasBillId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BILL_ID", nullable = false, insertable = false, updatable = false)
	public Bill getBill() {
		return this.bill;
	}

	public void setBill(Bill bill) {
		this.bill = bill;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PRODUCT_has_COLOR_COLOR_ID", referencedColumnName = "COLOR_ID", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PRODUCT_has_COLOR_PRODUCT_ID", referencedColumnName = "PRODUCT_ID", nullable = false, insertable = false, updatable = false) })
	public ProductHasColor getProductHasColor() {
		return this.productHasColor;
	}

	public void setProductHasColor(ProductHasColor productHasColor) {
		this.productHasColor = productHasColor;
	}

	@Column(name = "AMOUNT")
	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

}
