package javaweb.Entity;
// Generated Apr 27, 2021, 11:12:42 AM by Hibernate Tools 5.1.10.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "mydb")
public class Product implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Trademark trademark;
	private String name;
	private BigDecimal originalPrice;
	private BigDecimal price;
	private BigDecimal promotionPrice;
	private String image;
	private String description;
	private int ram;
	private int rom;
	private BigDecimal screenSize;
	private String frontCamera;
	private String backCamera;
	private int batteryCapacity;
	private String os;
	private String cpu;
	private String gpu;
	private String sim;
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<Rating> ratings = new HashSet<Rating>(0);
	private Set<ProductHasColor> productHasColors = new HashSet<ProductHasColor>(0);

	public Product() {
		this.trademark = new Trademark();
	}

	public Product(int id, Trademark trademark, String name, BigDecimal originalPrice, BigDecimal price,
			BigDecimal promotionPrice) {
		this.id = id;
		this.trademark = trademark;
		this.name = name;
		this.originalPrice = originalPrice;
		this.price = price;
		this.promotionPrice = promotionPrice;
	}

	public Product(int id, Trademark trademark, String name, BigDecimal originalPrice, BigDecimal price,
			BigDecimal promotionPrice, String image, String description, int ram, int rom,
			BigDecimal screenSize, String frontCamera, String backCamera, int batteryCapacity, String os,
			String cpu, String gpu, String sim, Set<Comment> comments, Set<Rating> ratings,
			Set<ProductHasColor> productHasColors) {
		this.id = id;
		this.trademark = trademark;
		this.name = name;
		this.originalPrice = originalPrice;
		this.price = price;
		this.promotionPrice = promotionPrice;
		this.image = image;
		this.description = description;
		this.ram = ram;
		this.rom = rom;
		this.screenSize = screenSize;
		this.frontCamera = frontCamera;
		this.backCamera = backCamera;
		this.batteryCapacity = batteryCapacity;
		this.os = os;
		this.cpu = cpu;
		this.gpu = gpu;
		this.sim = sim;
		this.comments = comments;
		this.ratings = ratings;
		this.productHasColors = productHasColors;
	}

	@Id
	@GeneratedValue(strategy =  GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = true, insertable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRADEMARK_ID", nullable = false)
	public Trademark getTrademark() {
		return this.trademark;
	}

	public void setTrademark(Trademark trademark) {
		this.trademark = trademark;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ORIGINAL_PRICE", nullable = false, precision = 20)
	public BigDecimal getOriginalPrice() {
		return this.originalPrice;
	}

	public void setOriginalPrice(BigDecimal originalPrice) {
		this.originalPrice = originalPrice;
	}

	@Column(name = "PRICE", nullable = false, precision = 20)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "PROMOTION_PRICE", nullable = false, precision = 20)
	public BigDecimal getPromotionPrice() {
		return this.promotionPrice;
	}

	public void setPromotionPrice(BigDecimal promotionPrice) {
		this.promotionPrice = promotionPrice;
	}

	@Column(name = "IMAGE", length = 500)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "RAM")
	public int getRam() {
		return this.ram;
	}

	public void setRam(int ram) {
		this.ram = ram;
	}

	@Column(name = "ROM")
	public int getRom() {
		return this.rom;
	}

	public void setRom(int rom) {
		this.rom = rom;
	}

	@Column(name = "SCREEN_SIZE", precision = 3, scale = 1)
	public BigDecimal getScreenSize() {
		return this.screenSize;
	}

	public void setScreenSize(BigDecimal screenSize) {
		this.screenSize = screenSize;
	}

	@Column(name = "FRONT_CAMERA", length = 45)
	public String getFrontCamera() {
		return this.frontCamera;
	}

	public void setFrontCamera(String frontCamera) {
		this.frontCamera = frontCamera;
	}

	@Column(name = "BACK_CAMERA", length = 45)
	public String getBackCamera() {
		return this.backCamera;
	}

	public void setBackCamera(String backCamera) {
		this.backCamera = backCamera;
	}

	@Column(name = "BATTERY_CAPACITY")
	public int getBatteryCapacity() {
		return this.batteryCapacity;
	}

	public void setBatteryCapacity(int batteryCapacity) {
		this.batteryCapacity = batteryCapacity;
	}

	@Column(name = "OS", length = 100)
	public String getOs() {
		return this.os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	@Column(name = "CPU", length = 100)
	public String getCpu() {
		return this.cpu;
	}

	public void setCpu(String cpu) {
		this.cpu = cpu;
	}

	@Column(name = "GPU", length = 100)
	public String getGpu() {
		return this.gpu;
	}

	public void setGpu(String gpu) {
		this.gpu = gpu;
	}

	@Column(name = "SIM", length = 100)
	public String getSim() {
		return this.sim;
	}

	public void setSim(String sim) {
		this.sim = sim;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Rating> getRatings() {
		return this.ratings;
	}

	public void setRatings(Set<Rating> ratings) {
		this.ratings = ratings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductHasColor> getProductHasColors() {
		return this.productHasColors;
	}

	public void setProductHasColors(Set<ProductHasColor> productHasColors) {
		this.productHasColors = productHasColors;
	}

}
