package javaweb.Entity;
// Generated Apr 27, 2021, 11:12:42 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductHasColorHasBillId generated by hbm2java
 */
@Embeddable
public class ProductHasColorHasBillId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int productHasColorColorId;
	private int productHasColorProductId;
	private int billId;

	public ProductHasColorHasBillId() {
	}

	public ProductHasColorHasBillId(int productHasColorColorId, int productHasColorProductId, int billId) {
		this.productHasColorColorId = productHasColorColorId;
		this.productHasColorProductId = productHasColorProductId;
		this.billId = billId;
	}

	@Column(name = "PRODUCT_has_COLOR_COLOR_ID", nullable = false)
	public int getProductHasColorColorId() {
		return this.productHasColorColorId;
	}

	public void setProductHasColorColorId(int productHasColorColorId) {
		this.productHasColorColorId = productHasColorColorId;
	}

	@Column(name = "PRODUCT_has_COLOR_PRODUCT_ID", nullable = false)
	public int getProductHasColorProductId() {
		return this.productHasColorProductId;
	}

	public void setProductHasColorProductId(int productHasColorProductId) {
		this.productHasColorProductId = productHasColorProductId;
	}

	@Column(name = "BILL_ID", nullable = false)
	public int getBillId() {
		return this.billId;
	}

	public void setBillId(int billId) {
		this.billId = billId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductHasColorHasBillId))
			return false;
		ProductHasColorHasBillId castOther = (ProductHasColorHasBillId) other;

		return (this.getProductHasColorColorId() == castOther.getProductHasColorColorId())
				&& (this.getProductHasColorProductId() == castOther.getProductHasColorProductId())
				&& (this.getBillId() == castOther.getBillId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductHasColorColorId();
		result = 37 * result + this.getProductHasColorProductId();
		result = 37 * result + this.getBillId();
		return result;
	}

}
