package javaweb.Entity;
// Generated Apr 27, 2021, 11:12:42 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductHasColor generated by hbm2java
 */
@Entity
@Table(name = "product_has_color", catalog = "mydb")
public class ProductHasColor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ProductHasColorId id;
	private Color color;
	private Product product;
	private int amount;
	private Set<ProductHasColorHasBill> productHasColorHasBills = new HashSet<ProductHasColorHasBill>(0);

	public ProductHasColor() {
	}

	public ProductHasColor(ProductHasColorId id, Color color, Product product, int amount) {
		this.id = id;
		this.color = color;
		this.product = product;
		this.amount = amount;
	}

	public ProductHasColor(ProductHasColorId id, Color color, Product product, int amount,
			Set<ProductHasColorHasBill> productHasColorHasBills) {
		this.id = id;
		this.color = color;
		this.product = product;
		this.amount = amount;
		this.productHasColorHasBills = productHasColorHasBills;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "colorId", column = @Column(name = "COLOR_ID", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "PRODUCT_ID", nullable = false)) })
	public ProductHasColorId getId() {
		return this.id;
	}

	public void setId(ProductHasColorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "COLOR_ID", nullable = true, insertable = false, updatable = false)
	public Color getColor() {
		return this.color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PRODUCT_ID", nullable = true, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "AMOUNT", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productHasColor")
	public Set<ProductHasColorHasBill> getProductHasColorHasBills() {
		return this.productHasColorHasBills;
	}

	public void setProductHasColorHasBills(Set<ProductHasColorHasBill> productHasColorHasBills) {
		this.productHasColorHasBills = productHasColorHasBills;
	}

}
