package javaweb.Entity;
// Generated Apr 27, 2021, 11:12:42 AM by Hibernate Tools 5.1.10.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Promotion generated by hbm2java
 */
@Entity
@Table(name = "promotion", catalog = "mydb")
public class Promotion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private BigDecimal value;
	private byte expired;
	private Set<Bill> bills = new HashSet<Bill>(0);

	public Promotion() {
	}

	public Promotion(int id, BigDecimal value, byte expired) {
		this.id = id;
		this.value = value;
		this.expired = expired;
	}

	public Promotion(int id, BigDecimal value, byte expired, Set<Bill> bills) {
		this.id = id;
		this.value = value;
		this.expired = expired;
		this.bills = bills;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "VALUE", nullable = false, precision = 5)
	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

	@Column(name = "EXPIRED", nullable = false)
	public byte getExpired() {
		return this.expired;
	}

	public void setExpired(byte expired) {
		this.expired = expired;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "promotion")
	public Set<Bill> getBills() {
		return this.bills;
	}

	public void setBills(Set<Bill> bills) {
		this.bills = bills;
	}

}
