package javaweb.Entity;
// Generated Apr 11, 2021, 1:55:39 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RatingId generated by hbm2java
 */
@Embeddable
public class RatingId implements java.io.Serializable {

	private int productId;
	private String accountUsername;

	public RatingId() {
	}

	public RatingId(int productId, String accountUsername) {
		this.productId = productId;
		this.accountUsername = accountUsername;
	}

	@Column(name = "PRODUCT_ID", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "ACCOUNT_USERNAME", nullable = false, length = 20)
	public String getAccountUsername() {
		return this.accountUsername;
	}

	public void setAccountUsername(String accountUsername) {
		this.accountUsername = accountUsername;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RatingId))
			return false;
		RatingId castOther = (RatingId) other;

		return (this.getProductId() == castOther.getProductId())
				&& ((this.getAccountUsername() == castOther.getAccountUsername())
						|| (this.getAccountUsername() != null && castOther.getAccountUsername() != null
								&& this.getAccountUsername().equals(castOther.getAccountUsername())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + (getAccountUsername() == null ? 0 : this.getAccountUsername().hashCode());
		return result;
	}

}
