package javaweb.Entity;
// Generated Apr 11, 2021, 1:55:39 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Trademark generated by hbm2java
 */
@Entity
@Table(name = "trademark", catalog = "mydb")
public class Trademark implements java.io.Serializable {

	private int id;
	private String name;

	public Trademark() {
	}

	public Trademark(int id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id
	
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
